version: '3.4'

services:
  visp:
    image: visp:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    volumes:
      - type: bind
        source: ..
        target: /root/visp-ws/tracking
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /dev
        target: /dev
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    command: tail -F anything
